# Site Information
baseurl: ""
description: "Musings of a startup junkie and Ruby on Rails nerd."
header-img: /img/home-bg.jpg
title: Millarian
full_description: "Curtis Miller is a Ruby on Rails and JavaScript web developer based in Phoenix, Arizona."
full_title: Millarian -- Curtis Miller's Developer Blog
url: "https://millarian.com"

# My Info
author: Curtis Miller
twitter_username:  curtism
github_username:   curtis
linkedin_username: curtm95
gravatar_hash: 0cc10d016d72b66a06590a1d2678f68b

company:
  name: Velocity Labs
  url: http://velocitylabs.io

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
