# Site Information
baseurl: ""
description: "Musings of a startup junkie and Ruby on Rails nerd."
header-img: /img/home-bg.jpg
title: Millarian
full_description: "Curtis Miller is a Ruby on Rails and JavaScript web developer based in Phoenix, Arizona."
full_title: Curtis Miller | Ruby on Rails | JavaScript | Web Development
url: "http://millarian.com"

# My Info
author: Curtis Miller
twitter_username:  curtism
github_username:   curtis
linkedin_username: curtm95

company:
  name: Velocity Labs
  url: http://velocitylabs.io

# Build Settings
markdown: kramdown
highlighter: pygments
permalink: /:categories/:title/
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
